# Generated by Django 5.2 on 2025-05-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "สายสุขภาพ"),
                            ("engineering", "สายวิศวกรรม"),
                            ("architecture", "สายสถาปัตยกรรม"),
                            ("language", "สายภาษา"),
                            ("volunteer", "ค่ายจิตอาสา"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("participants", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=200)),
                ("fee", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
