# Generated by Django 5.2 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camp",
            name="image_url",
        ),
        migrations.AddField(
            model_name="camp",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="camp_images/"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "สายสุขภาพ"),
                    ("engineering", "สายวิศวกรรม"),
                    ("architecture", "สายสถาปัตยกรรม"),
                    ("language", "สายภาษา"),
                    ("volunteer", "ค่ายจิตอาสา"),
                    ("Digital/IT", "ดิจิตอล/ไอที"),
                ],
                max_length=20,
            ),
        ),
    ]
