# Generated by Django 5.2 on 2025-05-04 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0002_remove_camp_image_url_camp_image_alter_camp_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camp",
            name="camp_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camp",
            name="camp_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camp",
            name="contact_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camp",
            name="mode",
            field=models.CharField(
                choices=[("online", "ออนไลน์"), ("onsite", "ออนไซต์")],
                default=datetime.datetime(
                    2025, 5, 4, 7, 58, 34, 168209, tzinfo=datetime.timezone.utc
                ),
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="camp",
            name="organizer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="date",
            field=models.DateField(),
        ),
    ]
