# Generated by Django 5.2 on 2025-05-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0003_camp_application_deadline_camp_camp_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "สายสุขภาพ"),
                    ("engineering", "สายวิศวกรรม"),
                    ("architecture", "สายสถาปัตยกรรม"),
                    ("language", "สายภาษา"),
                    ("volunteer", "ค่ายจิตอาสา"),
                    ("Digital IT", "ดิจิตอล ไอที"),
                ],
                max_length=20,
            ),
        ),
    ]
