# Generated by Django 5.2 on 2025-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0004_alter_camp_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camp",
            name="date",
        ),
    ]
