# Generated by Django 5.2 on 2025-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0005_remove_camp_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="camp",
            name="category",
            field=models.CharField(
                choices=[
                    ("health", "สายสุขภาพ"),
                    ("engineering", "สายวิศวกรรม"),
                    ("architecture", "สายสถาปัตยกรรม"),
                    ("language", "สายภาษา"),
                    ("volunteer", "ค่ายจิตอาสา"),
                    ("Digital IT", "สายดิจิตอล ไอที"),
                ],
                max_length=20,
            ),
        ),
    ]
