# Generated by Django 5.2 on 2025-05-05 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0006_camp_approved_alter_camp_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("m1", "ม.1"),
                            ("m2", "ม.2"),
                            ("m3", "ม.3"),
                            ("m4", "ม.4"),
                            ("m5", "ม.5"),
                            ("m6", "ม.6"),
                            ("other", "อื่นๆ"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "other_grade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hobbies", models.TextField(blank=True)),
                ("interests", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
