# Generated by Django 5.2 on 2025-05-03 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Camp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organizer_name", models.CharField(max_length=100)),
                ("phone_num", models.CharField(max_length=15)),
                ("camp_name", models.CharField(max_length=200)),
                ("detail_camp", models.TextField()),
                (
                    "upload_file",
                    models.FileField(blank=True, null=True, upload_to="camp_files/"),
                ),
                ("typeof_camp", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("final_date", models.DateField()),
                ("add_detail", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                ("num_candi", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("candi_proper", models.TextField()),
                ("place", models.CharField(max_length=200)),
                ("ig", models.URLField(blank=True)),
                ("facebook", models.URLField(blank=True)),
                ("line", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(max_length=254)),
                ("linkcamp", models.URLField(blank=True)),
                ("organize_camp", models.CharField(max_length=200)),
                ("detail_activity", models.TextField()),
                (
                    "poster",
                    models.ImageField(blank=True, null=True, upload_to="camp_posters/"),
                ),
                ("submit", models.DateTimeField(auto_now_add=True)),
                ("proof", models.FileField(blank=True, null=True, upload_to="proofs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="camps.campcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("major", models.CharField(blank=True, max_length=100)),
                ("grade", models.CharField(blank=True, max_length=10)),
                ("hobby", models.CharField(blank=True, max_length=200)),
                ("interest", models.CharField(blank=True, max_length=200)),
                ("saved_camps", models.ManyToManyField(blank=True, to="camps.camp")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
