# Generated by Django 5.2 on 2025-05-03 16:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camp",
            name="organize_camp",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="proof",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="typeof_camp",
        ),
        migrations.AlterField(
            model_name="camp",
            name="add_detail",
            field=models.TextField(
                blank=True, null=True, verbose_name="รายละเอียดเพิ่มเติม"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="camp_name",
            field=models.CharField(max_length=200, verbose_name="ชื่อแคมป์"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="candi_proper",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="คุณสมบัติผู้สมัคร"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="camps.campcategory",
                verbose_name="หมวดหมู่",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="detail_activity",
            field=models.TextField(
                blank=True, null=True, verbose_name="รายละเอียดกิจกรรม"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="detail_camp",
            field=models.TextField(verbose_name="รายละเอียดแคมป์"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="due_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="วันครบกำหนด"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="อีเมล"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="final_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="วันที่สิ้นสุด"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="ig",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="line",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Line ID"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="linkcamp",
            field=models.URLField(blank=True, null=True, verbose_name="ลิงก์แคมป์"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="num_candi",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="จำนวนผู้สมัคร"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="organizer_name",
            field=models.CharField(max_length=100, verbose_name="ชื่อผู้จัด"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="phone_num",
            field=models.CharField(max_length=20, verbose_name="เบอร์โทร"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="place",
            field=models.CharField(max_length=200, verbose_name="สถานที่"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="posters/", verbose_name="โปสเตอร์"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ราคา",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="วันที่เริ่ม"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="submit",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่ส่ง"),
        ),
        migrations.AlterField(
            model_name="camp",
            name="upload_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/", verbose_name="ไฟล์อัปโหลด"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="เว็บไซต์"),
        ),
    ]
