# Generated by Django 5.2 on 2025-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0002_remove_camp_organize_camp_remove_camp_proof_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camp",
            name="add_detail",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="candi_proper",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="final_date",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="linkcamp",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="num_candi",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="price",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="upload_file",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="website",
        ),
        migrations.AddField(
            model_name="camp",
            name="duration_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="จำนวนวัน"
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="duration_year",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="ปี"),
        ),
        migrations.AddField(
            model_name="camp",
            name="seats",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="จำนวนที่นั่ง"
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="time_range",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ช่วงเวลา"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="อีเมล"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="organizer_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ชื่อผู้จัด"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="phone_num",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="เบอร์โทร"
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="place",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="สถานที่"
            ),
        ),
    ]
