# Generated by Django 4.2 on 2025-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
